services:
  - type: web
    name: phytosense-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python download_model.py
    startCommand: gunicorn "app:create_app()" --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11"
